package com.example.project1.ui.detail

import com.example.project1.data.local.Friend

object DataDummy {
    val friendList = listOf(
        Friend(
            id = null,
            userId = null,
            name = "Galih Pratama",
            schoolId = null,
            phoneNumber = "0897641239912",
            apiToken = null,
            photo = null,
            schoolName = "International High School",
            deviceToken = null,
            createdAt = null,
            updatedAt = null,
            likeByYou = null,
        ),
        Friend(
            id = null,
            userId = null,
            name = "Pramata Indah",
            schoolId = null,
            phoneNumber = "0897641239912",
            apiToken = null,
            photo = null,
            schoolName = "National High School",
            deviceToken = null,
            createdAt = null,
            updatedAt = null,
            likeByYou = null,
        ),
        Friend(
            id = null,
            userId = null,
            name = "Bulan Ramadani",
            schoolId = null,
            phoneNumber = "0897641239912",
            apiToken = null,
            photo = null,
            schoolName = "Region High School",
            deviceToken = null,
            createdAt = null,
            updatedAt = null,
            likeByYou = null,
        ),
        Friend(
            id = null,
            userId = null,
            name = "Maruchan",
            schoolId = null,
            phoneNumber = "08927329188878",
            apiToken = null,
            photo = null,
            schoolName = "National High School",
            deviceToken = null,
            createdAt = null,
            updatedAt = null,
            likeByYou = null,
        ),
        Friend(
            id = null,
            userId = null,
            name = "Pangestu",
            schoolId = null,
            phoneNumber = "08927329188878",
            apiToken = null,
            photo = null,
            schoolName = "National High School",
            deviceToken = null,
            createdAt = null,
            updatedAt = null,
            likeByYou = null,
        ),
        Friend(
            id = null,
            userId = null,
            name = "Berlianan",
            schoolId = null,
            phoneNumber = "08927329188878",
            apiToken = null,
            photo = null,
            schoolName = "National High School",
            deviceToken = null,
            createdAt = null,
            updatedAt = null,
            likeByYou = null,
        )
    )
}